r-base=3.4.*
r-irkernel=0.7*
r-plyr=1.8*
r-devtools=1.13*
r-tidyverse=1.1*
r-shiny=1.0.*
r-rmarkdown=1.5*
r-forecast=8.0*
r-rsqlite=1.1*
r-reshape2=1.4*
r-nycflights13=0.2*
r-caret=6.0*
r-rcurl=1.95*
r-crayon=1.3*
r-randomforest=4.6*
